service: start-stop-instances

frameworkVersion: "3"

provider:
  name: aws
  region: us-east-2
  runtime: python3.8
  versionFunctions: false

functions:
  cronUpHandler:
    handler: up.run
    events:
      # Start stopped instances every week day at 10:00 AM
      - schedule: cron(0 10 ? * MON-FRI *)
  cronDownHandler:
    handler: down.run
    events:
      # Stop instances every week day at 08:00 PM
      - schedule: cron(0 20 ? * MON-FRI *)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    usePipenv: false
