name: Deploy master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
          with:
            node-version: 16

      - name: Setup Python
        uses: actions/setup-python@v4
          with:
            python-version: 3.8 

      - name: Serverless Deploy
        uses: dhollerbach/actions.serverless-with-python-requirements@v2        
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
